apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-connect-to-kafka
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: kafka
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: kafka-connect