apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"wiki-processor","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"wiki-processor"}},"template":{"metadata":{"labels":{"app":"wiki-processor"}},"spec":{"containers":[{"command":["faust","-A","wiki_stream_processor","worker","-l","info"],"env":[{"name":"ELASTICSEARCH_HOST","value":"http://elasticsearch:9200"},{"name":"KAFKA_BROKER","value":"kafka:9092"},{"name":"TOPIC_NAME","value":"wikipedia-events"},{"name":"FILTERED_TOPIC_NAME","value":"filtered-wikipedia-events"},{"name":"ES_INDEX","value":"filtered-wikipedia-events"}],"image":"amsg08/wiki-processor:latest","name":"wiki-processor"}]}}}}
  creationTimestamp: "2025-05-08T13:14:56Z"
  generation: 3
  name: wiki-processor
  namespace: default
  resourceVersion: "12982"
  uid: ab7d9723-5166-43ce-9f16-63be6ed5a589
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: wiki-processor
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8000"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: wiki-processor
    spec:
      containers:
      - command:
        - faust
        - -A
        - wiki_stream_processor
        - worker
        - -l
        - info
        env:
        - name: ELASTICSEARCH_HOST
          value: http://elasticsearch:9200
        - name: KAFKA_BROKER
          value: kafka:9092
        - name: TOPIC_NAME
          value: wikipedia-events
        - name: FILTERED_TOPIC_NAME
          value: filtered-wikipedia-events
        - name: ES_INDEX
          value: filtered-wikipedia-events
        image: amsg08/wiki-processor:latest
        imagePullPolicy: Always
        name: wiki-processor
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2025-05-08T13:14:56Z"
    lastUpdateTime: "2025-05-08T14:50:52Z"
    message: ReplicaSet "wiki-processor-68f4857457" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-05-08T15:06:57Z"
    lastUpdateTime: "2025-05-08T15:06:57Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 3
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
