apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-exporter
  labels:
    app: elasticsearch-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-exporter
  template:
    metadata:
      labels:
        app: elasticsearch-exporter
    spec:
      containers:
      - name: elasticsearch-exporter
        image: justwatch/elasticsearch_exporter:latest
        args:
          - --es.uri=http://elasticsearch:9200
        ports:
        - containerPort: 9114
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-exporter
  labels:
    app: elasticsearch-exporter
spec:
  ports:
  - port: 9114
    targetPort: 9114
  selector:
    app: elasticsearch-exporter