apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
    component: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      scrape_timeout: 10s
      external_labels:
        monitor: 'wiki-pipeline'
        environment: 'production'

    scrape_configs:
      # Kafka JMX Metrics
      - job_name: 'kafka-jmx'
        metrics_path: /metrics
        static_configs:
          - targets: ['kafka:7071']
        relabel_configs:
          - source_labels: [__address__]
            target_label: instance
            regex: '(.*):\d+'
            replacement: '${1}'

      # Kafka Exporter (Consumer Lag)
      - job_name: 'kafka-exporter'
        static_configs:
          - targets: ['kafka-exporter:9308']
        metrics_path: /metrics
        relabel_configs:
          - source_labels: [__address__]
            target_label: instance
            regex: '(.*):\d+'
            replacement: 'kafka-cluster'

      # Elasticsearch Metrics
      - job_name: 'elasticsearch-exporter'
        static_configs:
          - targets: ['elasticsearch-exporter:9114']
        metrics_path: /metrics
        params:
          format: ['prometheus']

      # Node Metrics
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter:9100']
        metrics_path: /metrics

      # Wiki Producer Application
      - job_name: 'wiki-producer'
        metrics_path: /metrics
        static_configs:
          - targets: ['wiki-producer:8000']
        relabel_configs:
          - source_labels: [__address__]
            target_label: job
            replacement: 'wiki-producer'

      # Wiki Processor (Faust)
      - job_name: 'wiki-processor'
        metrics_path: /metrics
        static_configs:
          - targets: ['wiki-processor:6066']
        relabel_configs:
          - source_labels: [__address__]
            target_label: job
            replacement: 'wiki-processor'

      # Kafka UI Metrics
      - job_name: 'kafka-ui'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['kafka-ui:8080']

      # Kubernetes Pods
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name

    rule_files:
      - /etc/prometheus/rules.yml