apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-producer
  labels:
    app: wiki-producer
    component: kafka-producer
    monitoring: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki-producer
  template:
    metadata:
      labels:
        app: wiki-producer
        component: kafka-producer
        monitoring: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      restartPolicy: Always
      containers:
      - name: wiki-producer
        image: amsg08/wiki-producer:latest
        ports:
        - containerPort: 8000
          name: metrics
          protocol: TCP
        - containerPort: 8001
          name: health
          protocol: TCP
        env:
        - name: KAFKA_BROKER
          value: kafka:9092
        - name: TOPIC_NAME
          value: wikipedia-events
        - name: ELASTICSEARCH_HOST
          value: http://elasticsearch:9200
        - name: METRICS_PORT
          value: "8000"
        - name: HEALTH_PORT
          value: "8001"
        - name: LOG_LEVEL
          value: "INFO"
        command: ["python", "wiki_producer.py"]
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: wiki-producer
  labels:
    app: wiki-producer
    component: kafka-producer
spec:
  ports:
  - name: metrics
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: health
    port: 8001
    targetPort: 8001
    protocol: TCP
  selector:
    app: wiki-producer