apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki-producer
  template:
    metadata:
      labels:
        app: wiki-producer
    spec:
      containers:
      - name: wiki-producer
        image: amsg08/wiki-producer:latest
        env:
        - name: KAFKA_BROKER
          value: "kafka:9092"
        - name: ELASTICSEARCH_HOST
          value: "http://elasticsearch:9200"
        - name: TOPIC_NAME
          value: "wikipedia-events"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-stream-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki-stream-processor
  template:
    metadata:
      labels:
        app: wiki-stream-processor
    spec:
      containers:
      - name: wiki-stream-processor
        image: amsg08/wiki-stream-processor:latest
        env:
        - name: KAFKA_BROKER
          value: "kafka:9092"
        - name: ELASTICSEARCH_HOST
          value: "http://elasticsearch:9200"

---
apiVersion: v1
kind: Service
metadata:
  name: wiki-producer-service
spec:
  selector:
    app: wiki-producer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: wiki-stream-processor-service
spec:
  selector:
    app: wiki-stream-processor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
