apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-connect-jmx-config
data:
  connect.yml: |
    startDelaySeconds: 0
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    rules:
      - pattern: 'kafka.connect<type=connect-worker-metrics, client-id="(.+)"><>([^:]+)'
        name: kafka_connect_worker_$2
        labels:
          client_id: "$1"
        type: GAUGE

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-connect
spec:
  selector:
    app: kafka-connect
  ports:
    - name: rest-api
      port: 8083
      targetPort: 8083
    - name: jmx
      port: 5556
      targetPort: 5556

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-connect
  template:
    metadata:
      labels:
        app: kafka-connect
    spec:
      initContainers:
        - name: jmx-exporter-downloader
          image: busybox:1.35
          command: ["/bin/sh", "-c"]
          args:
            - |
              mkdir -p /opt/jmx-exporter
              wget -q -O /opt/jmx-exporter/jmx_prometheus_javaagent.jar https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.16.1/jmx_prometheus_javaagent-0.16.1.jar
          volumeMounts:
            - name: jmx-exporter
              mountPath: /opt/jmx-exporter
      containers:
        - name: kafka-connect
          image: confluentinc/cp-kafka-connect:latest
          ports:
            - containerPort: 8083
            - containerPort: 5556
          env:
            - name: CONNECT_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: CONNECT_REST_ADVERTISED_HOST_NAME
              value: kafka-connect
            - name: CONNECT_GROUP_ID
              value: connect-cluster
            - name: CONNECT_CONFIG_STORAGE_TOPIC
              value: connect-configs
            - name: CONNECT_OFFSET_STORAGE_TOPIC
              value: connect-offsets
            - name: CONNECT_STATUS_STORAGE_TOPIC
              value: connect-status
            - name: CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
              value: "1"
            - name: CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
              value: "1"
            - name: CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
              value: "1"
            - name: CONNECT_KEY_CONVERTER
              value: org.apache.kafka.connect.json.JsonConverter
            - name: CONNECT_VALUE_CONVERTER
              value: org.apache.kafka.connect.json.JsonConverter
            - name: CONNECT_INTERNAL_KEY_CONVERTER
              value: org.apache.kafka.connect.json.JsonConverter
            - name: CONNECT_INTERNAL_VALUE_CONVERTER
              value: org.apache.kafka.connect.json.JsonConverter
            - name: CONNECT_LOG4J_ROOT_LOGLEVEL
              value: INFO
            - name: CONNECT_PLUGIN_PATH
              value: /usr/share/java,/usr/share/confluent-hub-components
            - name: KAFKA_CONNECT_JMX_OPTS
              value: "-javaagent:/opt/jmx-exporter/jmx_prometheus_javaagent.jar=5556:/etc/jmx-exporter/connect.yml"
          volumeMounts:
            - name: jmx-exporter
              mountPath: /opt/jmx-exporter
            - name: jmx-config
              mountPath: /etc/jmx-exporter
      volumes:
        - name: jmx-exporter
          emptyDir: {}
        - name: jmx-config
          configMap:
            name: kafka-connect-jmx-config
