apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090
  selector:
    app: prometheus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
      annotations:
        prometheus.io/scrape: "false"
    spec:
      securityContext:
        fsGroup: 65534  # ✅ Corrected placement
      containers:
        - name: prometheus
          image: prom/prometheus:v2.47.0
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-data
              mountPath: /prometheus
          args:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
            - '--storage.tsdb.retention.time=7d'
            - '--web.enable-lifecycle'
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "250m"
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config
        - name: prometheus-data
          persistentVolumeClaim:
            claimName: prometheus-pvc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      scrape_timeout: 10s

    scrape_configs:
      - job_name: 'kafka'
        static_configs:
          - targets: ['kafka:9101']
        metrics_path: '/metrics'
        relabel_configs:
          - source_labels: [__address__]
            target_label: instance
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod

      - job_name: 'zookeeper'
        static_configs:
          - targets: ['zookeeper:9141']
        metrics_path: '/metrics'

      - job_name: 'kafka-connect'
        static_configs:
          - targets: ['kafka-connect:8083']
        metrics_path: '/metrics'

      - job_name: 'elasticsearch'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['elasticsearch-exporter:9114']

      - job_name: 'applications'
        metrics_path: '/metrics'
        static_configs:
          - targets:
              - 'wiki-stream-processor:6066'
              - 'wiki-producer:8000'
              - 'wiki-processor:8000'
        relabel_configs:
          - source_labels: [__address__]
            target_label: job
            regex: '(.*):\d+'
            replacement: '$1'

      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter:9100']

      - job_name: 'cadvisor'
        static_configs:
          - targets: ['cadvisor:8080']

      - job_name: 'blackbox'
        metrics_path: '/probe'
        params:
          module: [http_2xx]
        static_configs:
          - targets:
              - 'http://kibana:5601'
              - 'http://grafana:3000'
              - 'http://kafka-ui:8080'
              - 'http://prometheus:9090/-/healthy'
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: blackbox-exporter:9115
