apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-processor
  labels:
    app: wiki-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki-processor
  template:
    metadata:
      labels:
        app: wiki-processor
    spec:
      containers:
        - name: wiki-processor
          image: amsg08/wiki-processor:latest
          env:
            - name: ELASTICSEARCH_HOST
              value: http://elasticsearch:9200
            - name: KAFKA_BROKER
              value: kafka:9092
            - name: TOPIC_NAME
              value: wikipedia-events
            - name: FILTERED_TOPIC_NAME
              value: filtered-wikipedia-events
            - name: ES_INDEX
              value: filtered-wikipedia-events
          command: ["faust", "-A", "wiki_stream_processor", "worker", "-l", "info"]
          ports:
            - containerPort: 8001  # Prometheus metrics endpoint
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: wiki-processor
  labels:
    app: wiki-processor
spec:
  selector:
    app: wiki-processor
  ports:
    - name: http
      port: 8001
      targetPort: 8001
